all: p26 p31 p32 p33 p34 p41
p26:
	clang-20 -Wall -O3 -lm -o p26 p26.c
p31:
	clang-20 -Wall -O3 -lm -o p31 p31.c
p32:
	clang-20 -Wall -O3 -lm -o p32 p32.c
p33:
	clang-20 -Wall -O3 -lm -o p33 p33.c
p34:
	clang-20 -Wall -O3 -lm -o p34 p34.c
p41:
	clang-20 -Wall -O3 -lm -o p41 p41.c