all: p10 p11 p12 p13

p10:
	clang -Wall -g -std=c23 -o p10 p10.c p10f.c alocare_matrici.c

p11:
	clang -Wall -g -std=c23 -o p11 p11.c p11f.c

p12:
	clang -Wall -g -std=c23 -o p12 p12.c p12_3f.c alocare_matrici.c

p13:
	clang -Wall -g -std=c23 -o p13 p13.c p12_3f.c alocare_matrici.c