all: p11 p12 p13 p21_5 p31 p41

p11:
	clang -O3 -Wall -lm -o p11 p11.c
p12:
	clang -O3 -Wall -lm -o p12 p12.c
p13:
	clang -O3 -Wall -lm -o p13 p13.c
p21_5:
	clang -O3 -Wall -lm -o p21_5 p21_5.c
p31:
	clang -O3 -Wall -lm -o p31 p31.c
p41:
	clang -O3 -Wall -lm -o p41 p41.c fct.c
p42:
	clang -O3 -Wall -lm -o p42 p42.c fct.c
