allint: p11 p12 p13 p14 p15
allreal: p21

p11:
	clang-20 -Wall -O3 -lm -o p11 p11.c vectorint.c
p12:
	clang-20 -Wall -O3 -lm -o p12 p12.c vectorint.c
p13:
	clang-20 -Wall -O3 -lm -o p13 p13.c vectorint.c
p14:
	clang-20 -Wall -O3 -lm -o p14 p14.c vectorint.c
p15:
	clang-20 -Wall -O3 -lm -o p15 p15.c vectorint.c

p21:
	clang-20 -Wall -O3 -lm -o p21 p21.c vectorreal.c