all: p11 p12 p13

p11:
	clang -Wall -std=c23 -march=native -o p11 p11.c p11f.c -lm

p12:
	clang -Wall -std=c23 -march=native -o p12 p12.c p11f.c -lm

p13:
	clang -Wall -std=c23 -march=native -o p13 p13.c p13f.c -lm