all: p11 p12 p13 p21 p22

p11:
	clang -Wall -std=c23 -o p11 p11.c p11f.c alocare.c
p12:
	clang -Wall -std=c23 -lm -o p12 p12.c p12f.c alocare.c afisare.c
p13:
	clang -Wall -std=c23 -o p13 p13.c p13f.c alocare.c afisare.c
p21:
	clang -Wall -std=c23 -lm -o p21 p21.c p21f.c alocare.c
p22:
	clang -Wall -std=c23 -lm -o p22 p22.c p223f.c alocare.c
p23:
	clang -Wall -std=c23 -lm -o p23 p23.c p223f.c alocare.c